### ISSUE TITLE
Responsive Navbar

### ISSUE THREAD

**Issue by andreidimaano** [citrushack/Citrushack2021#12]
Create mobile-friendly Navbar

**Comment by andreidimaano** [comment]
Transition into a 
Left: MLH Banner
Middle: icon
Right: Burger Menu

**Comment by akanksha26281** [comment]
Can I work on this issue?

**Comment by codejeet** [comment]
> Can I work on this issue?

Go for it!

**Comment by akanksha26281** [comment]
> > Can I work on this issue?
> 
> Go for it!

Can you help me to get started and which technology is used in this repo Angular, Vue, React??
