### ISSUE TITLE
Scale down divs

### ISSUE THREAD

**Issue by andreidimaano** [citrushack/Citrushack2021#13]
All Divs are too tall

Scale down the divs

**Comment by rajbirjohar** [comment]
Can you clarify? Marketing wants each page to take up 100vh for each section.

**Comment by andreidimaano** [comment]
yeah!

i think 100vh is good but i think the content takes up too much space. The content should be scaled down a bit - buttons, text cards, etc.

**Comment by rajbirjohar** [comment]
Oh for sure. Thanks for specifying.
